[build]
  command = "npm run build"
  publish = ".svelte-kit/output/client"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  framework = "#custom"
  targetPort = 5173
